### ISSUE TITLE
Add Presets for layouts

### ISSUE THREAD

**Issue by GriffinStacey** [ryanabaker/F1T#20]
Add customizable & saved presets to have radar, telemetry and other windows in specific locations & at specific sizes on the display.

**Comment by ryanabaker** [comment]
Other examples include
 - What settings were toggled when the program shut down
 - Opacity of the OverlayView
 - Any other SettingView related item...

This will involve creating some class which will save the states of SettingView's on close to a flat file, which will then be loaded once the application restarts.

A side effect to this is that if the file does not exist, it means the application has been opened for the first time. (And we can prompt them with a new user tutorial or message)

**Comment by ryanabaker** [comment]
X Y Location on each module
Saved the settings on each module
